import { Amplify } from 'aws-amplify';

export default defineNuxtPlugin(() => {
  // amplify_outputs.json is generated by `npx ampx sandbox` and is gitignored.
  // import.meta.glob returns an empty object when no files match, allowing the
  // app to start without it (useful for testing and non-AWS environments).
  const configs = import.meta.glob('../amplify_outputs.json', {
    eager: true,
    import: 'default',
  });
  const configKey = Object.keys(configs)[0];
  if (configKey) {
    Amplify.configure(configs[configKey] as Parameters<typeof Amplify.configure>[0]);
  } else {
    console.warn(
      'Amplify configuration not found. Run `npx ampx sandbox` to enable AWS features.',
    );
  }
});
